function pB1dot = pb1dot_s(dq1,dq2,l1,l2,q1,q2)
%PB1DOT_S
%    pB1dot = PB1DOT_S(DQ1,DQ2,L1,L2,Q1,Q2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    09-Oct-2025 21:53:28

t2 = q1+q2;
t3 = cos(t2);
t4 = sin(t2);
pB1dot = [-dq1.*((l2.*t4)./2.0+l1.*sin(q1))-(dq2.*l2.*t4)./2.0;dq1.*((l2.*t3)./2.0+l1.*cos(q1))+(dq2.*l2.*t3)./2.0];
end
