function pB2dot = pb2dot_s(dq1,dq2,dq3,l1,l2,l3,q1,q2,q3)
%PB2DOT_S
%    pB2dot = PB2DOT_S(DQ1,DQ2,DQ3,L1,L2,L3,Q1,Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    09-Oct-2025 21:53:28

t2 = q1+q2;
t3 = cos(t2);
t4 = q3+t2;
t5 = sin(t2);
t6 = cos(t4);
t7 = sin(t4);
t8 = l2.*t3;
t9 = l2.*t5;
t10 = l3.*t6;
t11 = l3.*t7;
pB2dot = [-dq2.*(t9+t11)-dq3.*t11-dq1.*(t9+t11+l1.*sin(q1));dq2.*(t8+t10)+dq3.*t10+dq1.*(t8+t10+l1.*cos(q1))];
end
